# Font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
font_size 10

# Background
background #0f0b14
foreground #e6dff2

selection_background #3b2a4a
selection_foreground #ffffff

cursor #c084fc
cursor_text_color #0f0b14

# Black
color0  #0b0811
color8  #4b3a59

# Red
color1  #a8557a
color9  #c06a92

# Green
color2  #7c6aa6
color10 #9a85c9

# Yellow
color3  #b07aa1
color11 #c792c4

# Blue
color4  #7a6ccf
color12 #9c8cff

# Magenta
color5  #a855f7
color13 #c084fc

# Cyan
color6  #8a6fbf
color14 #b39ddb

# White
color7  #ddd6f3
color15 #f4efff

# Window
background_opacity 0.95
window_padding_width 8